spring.application.name=talenthub
spring.datasource.url=jdbc:postgresql://localhost:5432/TalentHub_DB
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.security.user.name=${SECURITY_USER}
spring.security.user.password=${SECURITY_PASSWORD}
logging.level.org.springframework.security=TRACE
jwt.secret=${JWT_SECRET}
jwt.expiration=86400000
logging.level.org.hibernate.tool.schema=DEBUG