package com.jobportal.talenthub.service.impl;

import com.jobportal.talenthub.service.JwtService;
import io.jsonwebtoken.Claims;
import io.jsonwebtoken.Jwts;
import io.jsonwebtoken.security.Keys;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.security.core.userdetails.UserDetails;
import org.springframework.stereotype.Service;

import javax.crypto.SecretKey;
import java.nio.charset.StandardCharsets;
import java.util.Date;

@Service
public class JwtServiceImpl implements JwtService {

    // Secret key used to digitally sign JWTs.
    //
    // The same key is used later to verify that the JWT
    // was actually generated by our application and
    // has not been modified.
    //
    // The value is loaded from application.properties
    // or application configuration.
    @Value("${jwt.secret}")
    private String secret;


    // JWT lifetime in milliseconds.
    //
    // Example:
    // 3600000 milliseconds = 1 hour.
    //
    // The value is loaded from application configuration.
    @Value("${jwt.expiration}")
    private long expiration;


    // =========================================================
    // CREATE SIGNING KEY
    // =========================================================
    //
    // Converts the configured secret String into a
    // cryptographic SecretKey.
    //
    // This key is used for:
    //
    // Generate JWT
    //      ↓
    // Sign JWT
    //
    // Validate JWT
    //      ↓
    // Verify Signature

    private SecretKey getSigningKey() {

        return Keys.hmacShaKeyFor(
                secret.getBytes(StandardCharsets.UTF_8)
        );
    }


    // =========================================================
    // EXTRACT JWT CLAIMS
    // =========================================================
    //
    // Parses the JWT and verifies its signature.
    //
    // If the signature is invalid or the token cannot
    // be parsed, the JWT library will reject the token.
    //
    // Returns the JWT payload/claims.

    private Claims extractAllClaims(String token) {

        return Jwts
                .parser()
                .verifyWith(getSigningKey())
                .build()
                .parseSignedClaims(token)
                .getPayload();
    }


    // =========================================================
    // GENERATE JWT
    // =========================================================
    //
    // Called after successful login.
    //
    // Flow:
    //
    // User Login
    //      ↓
    // Authentication successful
    //      ↓
    // generateToken(email)
    //      ↓
    // JWT created
    //      ↓
    // JWT returned to client

    @Override
    public String generateToken(String email) {

        // Build the JWT with the user's identity,
        // creation time and expiration time.
        return Jwts.builder()

                // Stores the user's email as the JWT subject.
                //
                // This becomes the identity used later
                // by the JWT authentication filter.
                .subject(email)

                // Records when the JWT was created.
                .issuedAt(new Date())

                // Defines when the JWT becomes invalid.
                .expiration(
                        new Date(
                                System.currentTimeMillis()
                                        + expiration
                        )
                )

                // Digitally signs the JWT.
                //
                // The server can later verify this signature
                // using the same SecretKey.
                .signWith(getSigningKey())

                // Converts the JWT builder into the final
                // compact token String.
                .compact();
    }


    // =========================================================
    // EXTRACT EMAIL FROM JWT
    // =========================================================

    @Override
    public String extractEmail(String token) {

        // The email was stored in the JWT subject
        // during token generation.
        return extractAllClaims(token).getSubject();
    }


    // =========================================================
    // EXTRACT EXPIRATION
    // =========================================================

    @Override
    public Date extractExpiration(String token) {

        // Returns the expiration timestamp stored
        // inside the JWT payload.
        return extractAllClaims(token).getExpiration();
    }


    // =========================================================
    // CHECK TOKEN EXPIRATION
    // =========================================================

    @Override
    public boolean isTokenExpired(String token) {

        // If expiration time is before the current time,
        // the JWT has expired.
        return extractExpiration(token)
                .before(new Date());
    }


    // =========================================================
    // VALIDATE JWT
    // =========================================================
    //
    // A token is considered valid when:
    //
    // 1. The email stored inside the JWT matches
    //    the currently authenticated UserDetails username.
    //
    // 2. The JWT has not expired.
    //
    // The JWT signature itself is also verified when
    // extractAllClaims() parses the signed token.

    @Override
    public boolean isTokenValid(
            String token,
            UserDetails userDetails) {

        // Compare:
        //
        // JWT subject
        //      VS
        // UserDetails username
        //
        // In TalentHub both represent the user's email.
        //
        // Also make sure the JWT has not expired.
        return userDetails
                .getUsername()
                .equals(extractEmail(token))
                && !isTokenExpired(token);
    }
}